### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by obbardc** [64studio/dibby#2]
We need a Debian package, repo and install instructions.

**Comment by obbardc** [comment]
The package has been created and is in the 64studio repo.

@danielhjames can you test it and write an install blurb in the `README`?

**Comment by danielhjames** [comment]
Awesome! I'll take care of this in the morning :-)

**Comment by danielhjames** [comment]
Package installed without a hitch on Debian 9.8, thanks! Initial documentation has been added in https://github.com/64studio/dibby/commit/1f34eeeef284307f1b0a41ba9058a0320f2b9dd0
