### ISSUE TITLE
Package groups as tasks

### ISSUE THREAD

**Issue by obbardc** [64studio/dibby#7]
Packages currently are installed in the project postinst script which is not ideal.

**Comment by obbardc** [comment]
The script `tasks/1000_openssh-server.sh` should be run if the task `openssh-server` has been selected, for instance.

**Comment by danielhjames** [comment]
So the config file would specify the tasks for the active project? I like this idea, as we could potentially host a large number of tasks within the dibby project without bloating the target images.

**Comment by obbardc** [comment]
Exactly, the config file for a project now has
`CONFIG_CUSTOM_TASKS="openssh-server xorg"`
and a separate script for each task in the `task` directory.

The `bootstrap` directory contains the minimal installation of the system.

**Comment by obbardc** [comment]
All done, just left to make some tasks!
