### ISSUE TITLE
Don't throw an error if the user doesn't specify any custom packages

### ISSUE THREAD

**Issue by danielhjames** [64studio/dibby#9]
I: dibby: running /home/daniel/64studio/git/dibby/bootstrap/1001_custom_packages.sh
Reading package lists... Done
Building dependency tree... Done
E: Unable to locate package CONFIG_CUSTOM_PACKAGES

**Comment by obbardc** [comment]
Interesting, it shouldn't run if the variable `$CONFIG_CUSTOM_PACKAGES` is empty or not set in user config.

**Comment by danielhjames** [comment]
Ah, I did specify a custom package but it looks like you already fixed the issue in https://github.com/64studio/dibby/commit/50753c9d9d43c6a6024e7ff00e772e0abc9418a8 thanks! I will test again.

**Comment by danielhjames** [comment]
Confirmed fixed :-)
